name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        go: [1.25]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Release caddy-cdn-ranges
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Install go tools # cSpell: words gopls golangci
        run: |
          go install golang.org/x/tools/gopls@latest && \
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Export Module Name
        id: export_module_name
        run: |
          TAG_NAME="${{ github.ref_name }}"
          MODULE_DIR="."
          if [[ "$TAG_NAME" == v2.* ]]; then
            MODULE_DIR="v2"
          fi
          echo "MODULE_DIR=$MODULE_DIR" >> "$GITHUB_OUTPUT"
          echo "MODULE_NAME=$(cd "$MODULE_DIR" && go mod edit -json | jq -r '.Module.Path')" >> "$GITHUB_OUTPUT"

      - name: Run linters # cSpell: words gofmt
        run: |
          gofmt -s -d $(find . -type f -name '*.go'| grep -v "/vendor/")
          golangci-lint run -v && golangci-lint run -v --exclude-dirs-use-default -e printf
        shell: bash
        working-directory: ${{ steps.export_module_name.outputs.MODULE_DIR }}

      - name: Run tests with coverage # cSpell: words coverprofile
        run: go test ./... -coverprofile=coverage.out
        working-directory: ${{ steps.export_module_name.outputs.MODULE_DIR }}

      - name: Publish code coverage # cSpell: words qltysh qlty
        uses: qltysh/qlty-action/coverage@v2
        with:
          files: ${{ steps.export_module_name.outputs.MODULE_DIR }}/coverage.out
          add-prefix: ${{ steps.export_module_name.outputs.MODULE_NAME }}
          verbose: true
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}

      - name: Create release from tag # cSpell: words ncipollo
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          makeLatest: true
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update code documentation
        run: |
          MODULE_PATH="${{ steps.export_module_name.outputs.MODULE_NAME }}"
          TAG_NAME="${{ github.ref_name }}"
          curl -fsSL "https://proxy.golang.org/$MODULE_PATH/@v/$TAG_NAME.info"
